language: java

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install: echo "skip 'gradle assemble' step"
script: ./gradlew build integrationTest --console=plain -Dorg.gradle.logging.level=info -x dokka --stacktrace -PexcludeTests=**/InfoIntegrationTest*

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_failure: cat /home/travis/build/manosbatsis/corbeans/corbeans-corda-webserver/build/reports/tests/test/index.html
