name: corbeans
baseurl: /corbeans
description: Corda integration for Spring Boot
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: docs
markdown: kramdown
